docs/docs/Introduction/intro.md
docusaurus.config.ts
src/css/custom.css

Added an intro page (sorry @leighajarett) and css classes for video embeds.

Added intro page

---

src/css/custom.css

Add video-container class

---

docusaurus.config.ts

Log broken links to see if deployment is fixed

---

docs/intro/before-you-begin/app-architecture.md

[Fix Typo] Update app-architecture.md

---

docs/Integrations/firebase/connect-to-firebase-setup.md

Text bold in connect-to-firebase-setup.md

---

package-lock.json
package.json
src/components/Feedback/index.js
yarn.lock

Add feedback 5 star rating widget
Linear ticket and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-540

Add feedback widget with gtag event

---

src/components/Feedback/index.js

Add value to feedback analytics

---

firebase.json

Add updates to redirects

---

docs/resources/ui/widgets/built-in-widgets/overview.md

Remove wrong file

---

firebase.json

Fix redirect from product

---

docs/resources/ui/widgets/widget-commonalities.md

…ionnalities.md
Add spacing between widget and from in the padding and alignment section

Add spacing between widget and from in the padding and alignment section

---

docs/ff-concepts/file-handling/clear-delete-media.md

Delete data allows for deleting from both Firebase and Supabase

[Update] what delete data does

---

firebase.json

Remove troubleshooting redirect

---

docs/resources/ui/pages/page-lifecycle.md

[Linear ticket](https://linear.app/flutterflow/issue/DEVR-603/docs-keyboard-shortcuts) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-603

Keyboard Shortcut

---

docs/resources/control-flow/backend-logic/api/streaming-api.md

This linked to Cloud Functions, but should link to Custom Functions (as the arcade shows).

Update link to custom functions

---

docs/resources/control-flow/backend-logic/api/streaming-api.md

The toggle is labelled "Process Stream*ing* Reponse".

Fix typo in SSE docs

---

docs/resources/projects/libraries.md

Adding Disabled Features info for libraries
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-628/add-info-about-lib-project-vs-app-project-to-libraries-documentation) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-628

Disabled Features Info in Libraries

---

docs/ff-concepts/adding-customization/custom-files.md
docs/ff-concepts/adding-customization/vscode-extension.md
docs/ff-concepts/navigation-routing/bottom-sheet.md
docs/ff-integrations/payments/braintree.md
docs/ff-integrations/streaming/mux/integrate-mux.md
docs/resources/control-flow/backend-logic/api/streaming-api.md
docs/resources/data-representation/custom-data-types.md
docs/resources/ui/components/creating-components.md
docs/resources/ui/components/using-components.md
docs/resources/ui/components/widget-builder-parameters.md
docs/resources/ui/widgets/built-in-widgets/calendar.md
docs/resources/ui/widgets/intro-widgets.md

Fix broken links and spelling correction
Linear ticket and [magic word](https://linear.app/docs/github#link-prs) Fixes 
[DEVR-632](https://linear.app/flutterflow/issue/DEVR-632/fix-broken-links)
[DEVR-634](https://linear.app/flutterflow/issue/DEVR-634/fix-spelling)

Fix broken links and spelling correction

---

firebase.json

Fix redirect links

---

firebase.json

Add redirects for widget loc refactors

---

firebase.json

Visiting https://docs.flutterflow.io/marketplace/creators-hub results in a redirect (301) loop. See https://flutterflow.slack.com/archives/C040YEEK68Z/p1728053166562709 for details

👯 Remove recursive Marketplace redirects

---

docs/resources/data-representation/app-state.md

Fix app state link

---

docs/testing-deployment-publishing/development-environments/development-environments.md

Typo Correction

---

firebase.json

Added Redirect for Properties Panel Broken Link
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-657/page-not-found) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-657

Added Redirect for Properties Panel Broken Link

---

docs/ff-concepts/adding-customization/vscode-extension.md

VS Code Extension: Fix enterprise url
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-674/small-url-addition-to-vscode-page) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-674

VS Code Extension: Fix enterprise url

---

docs/ff-integrations/authentication/supabase-auth/supabase-apple-auth.md

Update action name in header

---

docs/resources/projects/libraries.md

[Libraries] Added Supabase to the disabled features list
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-698/add-supabase-to-disabled-features-on-libraries) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-698

[Libraries] Added Supabase to disabled features list

---

docs/troubleshooting/index.md

[Troubleshooting] Update header
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-699/troubleshooting-guide) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-699

[Troubleshooting] Update header

---

docs/ff-concepts/file-handling/download-file.md

Update download action name

---

docs/ff-integrations/authentication/supabase-auth/auth-actions.md

Add correct info for auth providers for supabase

---

docs/ff-integrations/authentication/supabase-auth/email-supabase.md

Update this hyperlinks to their actual intentions

Remove "this" hyperlinks.

---

docs/marketplace/creators-hub/submission-criteria.md

This update adds library-specific submission criteria to the Marketplace submission guidelines. Key additions include:
- New section 1.6 clarifying that libraries cannot depend on other Marketplace libraries
- New section 5.15 requiring the use of Library Values for configurable elements
- New section 5.16 recommending automated tests (especially for libraries)
- Updated section 6.1 to include specific value criteria for paid libraries
These changes aim to ensure libraries in the Marketplace are secure, maintainable, and provide substantial value to users. The additions maintain consistency with existing documentation style while introducing important library-specific requirements and best practices.
Linear ticket and [magic word](https://linear.app/docs/github#link-prs) Fixes MKT-407

📚 Update Marketplace submission criteria for Libraries

---

docs/resources/control-flow/backend-logic/api/rest-api.md

Correct header name in provided example.

Correct header name

---

docs/resources/ui/widgets/composing-widgets/list-grid.md

Make Reorder section more prominent

---

docs/resources/ui/widgets/composing-widgets/list-grid.md

Fix header

---

docs/resources/ui/components/component-lifecycle.md

Replaces an Arcade
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-758/duplicate-videos-for-component-documentation-sections) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-758

Fixes DEVR-758: Replaces an Arcade

---

docs/testing-deployment-publishing/branching-collaboration/branching.md

Removed Merge V1 Info
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-873/remove-merge-v1-info) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-873

Removed Merge V1 Info

---

docs/ff-concepts/navigation-routing/deep-dynamic-linking.md

Fix deeplink YT link

---

docs/ff-concepts/design-system/design-system.md

`tertairy_button` -> `tertiary_button` in [Design System](https://docs.flutterflow.io/concepts/design-system) section.

doc: fix typo

---

docs/resources/projects/settings/mcp_server.md
docs/resources/projects/settings/project-setup.md
docs/resources/projects/settings/version-management.md

 MCP Server - Initial

---

docs/ff-concepts/animations/widget_animations.md
docs/ff-integrations/payments/razorpay.md
docs/resources/control-flow/backend-logic/api/soap-api.md
docs/resources/control-flow/backend-logic/api/streaming-api.md
docs/resources/control-flow/functions/utility-functions.md
docs/resources/control-flow/overview.md
docs/resources/control-flow/user-interactivity/forms/form-widgets/dropdown.md
docs/resources/ui/widgets/built-in-widgets/sticky-header.md
firebase.json

Update "Code Expression" to "Inline Function"
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-946/rename-code-expression-to-inline-function) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-946

Update "Code Expression" to "Inline Function"

---

docs/ff-concepts/animations/widget_animations.md
docs/ff-integrations/payments/razorpay.md
docs/resources/control-flow/backend-logic/api/soap-api.md
docs/resources/control-flow/backend-logic/api/streaming-api.md
docs/resources/control-flow/functions/utility-functions.md
docs/resources/control-flow/overview.md
docs/resources/control-flow/user-interactivity/forms/form-widgets/dropdown.md
docs/resources/ui/widgets/built-in-widgets/sticky-header.md

Add rename notice

---

docs/accounts-billing/plan-pricing.md

📆 Adjust date

---

static/css/table_style.css

Render the plan overview table better in dark mode

🌜 Add dark mode support for pricing table

---

docs/ff-concepts/notifications/push-notifications.md
docs/ff-integrations/ai/ai-agents.md

Add Permission Info
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-916/add-permissions-needed-on-ai-agents) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-916

Add Permission Info

---

docs/accounts-billing/new-pricing-comparison.md

Changed the Cloud Functions feature for the Free plan from unavailable (❌) to available (✅) in the pricing comparison documentation.
Fixes DEVR-990

✅ Update Cloud Functions availability in pricing table

---

docs/accounts-billing/new-pricing-comparison.md

Custom for the following features (enterprise) 
Project Count
API Endpoints
Number of Editors

updated enterprise pricing custom

---

src/js/chatbot.js

Running into limit error temporarily so will disable chatbot to see why this is happening

temp disable chatbot

---

docs/accounts-billing/plan-pricing.md

[typo] Remove extra ? from plan FAQS
