docs/ff-concepts/animations/hero_animations.md
docs/ff-concepts/animations/implicit_animations.md
docs/ff-concepts/animations/widget_animations.md
docs/ff-concepts/layout/building-layout.md
docs/ff-concepts/layout/responsive-layout.md
docs/ff-concepts/layout/responsive-widgets/conditional-builder-widget.md
docs/ff-concepts/layout/responsive-widgets/wrap-widget.md

Linear ticket and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-542

Fix more slugs

---

docs/ff-concepts/adding-customization/cloud-functions.md
docs/index.md
docusaurus.config.ts
package-lock.json
package.json
yarn.lock

Linear ticket and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-547 & Fixes DEVR-534

DocSearch + Analytics

---

docs/ff-concepts/localization-accessibility/add-multiple-languages.md
docs/ff-concepts/state-management/state-variables.md
docs/ff-concepts/state-management/widget-state.md
docs/intro/before-you-begin/app-architecture.md
docs/intro/before-you-begin/setting-up-flutterflow.md
docs/intro/ff-ui/builder.md
docs/intro/ff-ui/canvas.md
docs/intro/ff-ui/resource-hierarchy.md
docs/intro/ff-ui/storyboard.md
docs/intro/ff-ui/toolbar.md
docs/intro/ff-ui/widget-palette.md
docs/resources/control-flow/backend-logic/api/create-test-api-calls.md
docs/troubleshooting/push-notifications.md
firebase.json
static/robots.txt

Redirect Mappings from old URL to new URL + Add Robots.txt
Linear ticket and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-565, Fixes DEVR-545

Redirect Mappings

---

docs/testing-deployment-publishing/running-your-app/run-your-app.md

[Linear ticket](https://linear.app/flutterflow/issue/DEVR-580/local-run-hyperlink-is-not-correctly-set) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-580

[Fix] Local run link

---

docs/ff-concepts/adding-customization/custom-code.md

Fix a tiny typo
Linear ticket and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-588

Update custom-code.md to spell favorite with US spelling

---

docs/resources/control-flow/functions/action-blocks.md

notice that some actions are not available in the action block

[Update] action-blocks.md: Added notice on actions not supported in Action Block

---

docs/resources/data-representation/custom-data-types.md

On this section https://docs.flutterflow.io/resources/data-representation/custom-data-types/#accessing-custom-data-type  the example link doesn't work.
Linear ticket and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-593

[Fixed] Custom Data Type link update

---

docs/ff-integrations/database/local-sql/quickstart.md

SQLite was spelled SQLIte in the leftnav, so let's fix that.

Fix tiny casing mistake

---

docs/intro/before-you-begin/setting-up-flutterflow.md

Update minimum resolution in setup page.
1280x1084 is not a [common resolution][1], so probably was meant to be 1280x1024.
[1]: https://en.wikipedia.org/wiki/List_of_common_display_resolutions

Fix tiny typo in minimum resolution in setup docs

---

docs/testing-deployment-publishing/branching-collaboration/branching.md

Add close branch info
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-559/branching-documentation-is-out-of-date-with-the-recent-changes) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-559

Add close branch info

---

docs/ff-concepts/adding-customization/custom-widgets.md
docs/resources/ui/components/creating-components.md
docs/resources/ui/widgets/built-in-widgets/tooltip.md

Added info on widget as tooltip and widget builders for custom widget
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-646/rich-content-in-tooltip) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-646

Added info on widget as tooltip + widget builders for custom widget

---

docs/ff-concepts/adding-customization/vscode-extension.md

Added info on changing URL override for Beta and Enterprise version.
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-652/add-information-on-url-override-to-vscode-extension-docs) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-652

Added info on changing URL override for Beta and Enterprise version.

---

docs/resources/projects/libraries.md

Clarifiy how to revert project from Library to traditional project

Adding details on reverting lib publish

---

docs/testing-deployment-publishing/running-your-app/run-your-app.md

Update about Run Mode Links
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-686/update-doc-to-clarify-run-mode-link-visibility) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-686

Update about Run Mode Links

---

docs/ff-integrations/database/supabase/database-actions.md

Added Supabase Like filter info
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-714/supabase-like-filter-docs) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-714

Added Supabase Like filter info

---

docs/marketplace/creators-hub/submit-item-for-reivew.md

Updates marketplace submission docs for libraries
Linear ticket and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-709

Updating for libraries

---

docs/marketplace/submit-feedback.md

Update Marketplace feedback reporting docs to highlight how to contact creators and rate items from the item detail page.

📝 Update item feedback instructions

---

docs/ff-integrations/authentication/supabase-auth/auth-actions.md

[Linear ticket](https://linear.app/flutterflow/issue/DEVR-712/custom-redirecturl-in-supabase) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-712

Added Custom Redirect URL for Supabase Reset Password

---

docs/ff-concepts/adding-customization/custom-code.md

Added Dependency Page Info
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-693/add-dependency-page-info-to-docs) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-693

Added Dependency Page Info

---

docs/ff-concepts/adding-customization/custom-code.md

Added info on Using Unpublished Packages
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-730/[docs]-allow-github-repo-urls-for-package-dependencies) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-730

Added info on Using Unpublished Packages

---

docs/ff-concepts/design-system/design-system.md
docs/resources/projects/libraries.md

Added Library as Design System
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-737/libraries-as-design-systems) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-737

Added Library as Design System

---

docs/resources/projects/libraries.md

Added info on libraries with Firebase
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-740/add-details-on-firebase-support-for-libraries) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-740

Libraries support for Firebase

---

docs/resources/style-guide.md

Reference other common case names.

🍴 Add alternative case names

---

docs/testing-deployment-publishing/branching-collaboration/branching.md

Restore Branch Info
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-788/outdated-documentation-on-closing-branches) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-788

Restore Branch Info

---

docs/ff-integrations/firebase/connect-to-firebase-setup.md

Enable Billing for Cloud Storage
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-654/project-must-be-on-paid-plan-to-create-firebase-cloud-storage) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-654

Enable Billing for Cloud Storage

---

docs/ff-concepts/adding-customization/vscode-extension.md

Use VS code extension with FVM
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-718/docs-on-using-fvm-with-vscode-extension) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-718

Use VS code extension with FVM

---

docs/resources/projects/libraries.md
firebase.json

Library publishing restriction info
[Linear ticket ](https://linear.app/flutterflow/issue/DEVR-719/restrictions-for-already-deployed-project-while-publishing-library)and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-719, Fixes DEVR-798

Library publishing restriction info

---

docs/resources/ui/widgets/built-in-widgets/tooltip.md

Dynamic Content in Tooltip
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-767/document-workaround-for-dynamic-content-in-tooltips) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-767

Dynamic Content in Tooltip

---

docs/marketplace/creators-hub/submission-criteria.md

Expand Run Mode Link criteria for mobile-only and utility libraries
Updates section 4.1 (Functional Run Mode Link) to provide clear guidance for creators submitting items that cannot be fully demonstrated in Run Mode's web environment. This includes:
- Alternative demonstration methods for mobile-only features
- Guidelines for utility libraries (analytics, background services, etc.)
- Requirements for visual documentation and mockups
- Option to use published web deploy links instead of Run Mode URLs
This change addresses creator feedback regarding submissions of platform-specific features and utility libraries that require special demonstration approaches.
Linear ticket: Fixes MKT-512

🔍 Clarify Run Mode requirement for Marketplace submission

---

docs/marketplace/creators-hub/creators-hub.md
docs/marketplace/creators-hub/submit-item-for-review.md
docs/marketplace/index.md
firebase.json

Fix Typo for 'Submitting Item for Review' (Marketplace Doc) Url
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-819/fix-typo-in-documentation-url-path) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-819

Fix Typo in Marketplace Doc Url

---

docs/ff-integrations/payments/stripe.md

[Stripe] Added additional info related to cloud functions invoker permission
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-805/add-troubleshooting-point-for-cloud-functions-invoker) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-805

[Stripe] Added additional info related to cloud functions invoker permission

---

docs/ff-concepts/localization-accessibility/accessibility.md

Fixing typos in Accessibility documentation

Update accessibility.md typos

---

docs/ff-integrations/ai/ai-agents.md
docs/ff-integrations/payments/stripe.md

Updated Prerequisite in AI Agents
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-871/ai-agents-mention-needing-firebase-auth) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-871

Updated Prerequisite in AI Agents

---

docs/resources/projects/libraries.md

Fix the path to the page where you can import a library, as it's in a different section that what the docs said.
The documentation said that the Project Dependencies page is under App Settings, but it's actually under Project Setup - so this PR fixes that.

Fix navigation to the import libraries settings page

---

docs/ff-concepts/notifications/push-notifications.md

Add Section for Testing Push Notifications Cloud Function
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-867/point-to-pufs-cloud-function-testing-example-from-push-notifications) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-867

Add Section for Testing Push Notifications Cloud Function

---

docs/ff-concepts/navigation-routing/nav-overview.md

Updated the navigation overview docs and use page description text for nav links

Improved Navigation Overview docs wordings

---

docs/ff-concepts/design-system/design-system.md
docs/resources/control-flow/backend-logic/api/rest-api.md
docs/resources/projects/libraries.md

- 'iconmoon' → 'IcoMoon' in [Design System](https://docs.flutterflow.io/concepts/design-system) section.
- 'enablethe` → 'enable the' in [API Calls](https://github.com/tirth-patel-nc/flutterflow-documentation/blob/patch-1/docs/resources/control-flow/backend-logic/api/rest-api.md) section. 
- 'Libraries enables' → 'Libraries enable' in [Libraries](https://docs.flutterflow.io/resources/projects/libraries) section.

docs: fix typos

---

docs/ff-concepts/adding-customization/custom-code.md

FlutterFLow -> FlutterFlow in [Custom Code](https://docs.flutterflow.io/concepts/custom-code) section.

docs: fix typo

---

docs/generated-code/ff-app-state.md

Fix some formatting issues in [FF-App-State](https://docs.flutterflow.io/generated-code/ff-app-state) section.

docs: fix formatting

---

docs/ff-concepts/navigation-routing/deep-dynamic-linking.md

Branch: add warning about link generation failures

---

docs/ff-integrations/payments/stripe.md

Stripe Country Code Info Update
[Linear ticket](https://linear.app/flutterflow/issue/DEVR-844/stripe-or-clarify-whether-merchant-country-code-is-2-characters-or-3) and [magic word](https://linear.app/docs/github#link-prs) Fixes DEVR-844

Stripe Country Code Info Update

---

docs/accounts-billing/new-pricing-comparison.md

Changed the automated testing row to reflect '1 test per project' instead of '❌' for the relevant pricing tier in the comparison table.

🧪 Update automated testing limits for Growth

---

src/js/chatbot.js

Renamed the classes that should be pinned to be: 
* dify-chatbot-widget
* dify-chatbot-bubble-window
* dify-chatbot-bubble-button
Before the names were to generic (ex. the class was called dify), which meant headers that had "Modify" were pinned because it has "dify" in it
Thank you @PoojaB26 for pointing this out! 
After: 
Before: 
After: 
Before:

Fix UI issue where words with "modify" were being pinned to bottom of page
